image: node:13

stages:
  - test
  - build
  - deploy

# deploy for spec
# pages:
#   stage: deploy
#   script:
#   - python3 -V
#   - cd docs
#   - pip3 install -r requirements.txt
#   - sphinx-build -b html source build/html
#   - mv build/html/ ../public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master

# build dapp
build:
  stage: build
  script:
    - npm install
    - cd dapp
    - yarn install
    - CI=false yarn build
  artifacts:
    expire_in: 1 day
    paths:
    - dapp/build
  only:
  - master

# deploy dapp
pages:
  stage: deploy
  script:
    - mv dapp/build/ public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
    - public
  only:
  - master

contracts:
  stage: test
  image: node:13
  script:
  - git submodule init
  - git submodule update
  - npm install
  - npm run build
  - npm run test
  only:
  - merge_requests
