image: python:3.7-alpine

stages:
  - test
  - deploy

pages:
  stage: deploy
  script:
  - python3 -V
  - cd docs
  - pip3 install -r requirements.txt
  - sphinx-build -b html source build/html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master

contracts:
  stage: test
  image: node:13
  script:
  - git submodule init
  - git submodule update
  - npm install
  - npm run build
  - npm run test