image: node:13

stages:
  - test

contracts:
  stage: test
  image: node:13
  script:
  - git submodule init
  - git submodule update
  - npm install
  - npm run build
  - npm run test
  only:
  - merge_requests
